[Variables]
tThemeUpdater=Chủ đề tự động
tThemeUpdaterHelp=Cập nhật chủ đề dựa vào thời gian thực và sự thay đổi hình nền.[\13][\10]Nếu chủ để không tự động cập nhật, hãy thử tải lại lựa chọn này.
tSidebar=Luôn hiện tiện ích 
tSidebarHelp=Tạo ra một biểu tượng trong khay hệ thống để ẩn hoặc hiện tiện ích.[\13][\10]Các tiện ích sẽ xuất hiện trên cùng.
tUnlock=Hiệu ứng mở khóa
tUnlockHelp=Bật hiệu ứng khi mở khóa màn hình.[\13][\10]Cần dùng Task Schedule để hoạt động.[\13][\10]Chọn để cài đặt.