[Variables]
; --- Context menu ---
tEdit=Edit
tSmall=Small
tMedium=Medium
tWide=Wide
tLarge=Large
tRemoveWidget=Remove widget
tEditWidgets=Edit widgets
tSave=Save
; --- Clock ---
tClock=Clock
tClockDescription=Show the current time
tClockShowSeconds=Show seconds
; --- Calendar ---
tCalendar=Calendar
tCalendarDescription=Displaying the current month
tCalendarSundayWeek=Week from Sunday
tWeekDays=S,M,T,W,T,F,S
; --- Activity Monitor ---
tActivityMonitor=Activity monitor
tActivityMonitorDescription=Tracking system resources
tActivityMonitorAvailableValues=Available values
tActivityMonitorItem1=Resource 1
tActivityMonitorItem2=Resource 2
tActivityMonitorItem3=Resource 3
tActivityMonitorItem4=Resource 4
; --- Weather ---
tWeather=Weather
tWeatherDescription=Current weather
tWeatherAPIKey=OpenWeatherMap API key
tWeatherCity=City
; --- Notes ---
tNotes=Notes
tNotesDescription=Quick note on your desktop
; --- Music ---
tMusic=Music
tMusicDescription=See what's playing right now
tNoMusic=Nothing's playing
tApp=App
; --- Volume ---
tVolume=Volume
tVolumeDescription=Control playback volume
; --- Settings ---
tWelcome=Welcome
tWidgets=Widgets
tSettings=Settings
tAbout=About
tVersion=Version
tAdd=Add
; --- Appearence ---
tAppearence=Design
tTheme=Theme
tLightTheme=Light
tDarkTheme=Dark
tAutoTheme=Auto
tColorTheme=Color
tBackgroundColor=Background color
tForegroundColor=Text color
tColorThemeDescription=Background and text colors are defined by the colors of your desktop wallpaper
tFrom=from
tTo=to
; --- Advanced ---
tAdvanced=Advanced
tWidgetSize=Size widget
tWidgetPadding=Distance between widgets
tWidgetRadius=Rounding corners
tFontFace=Font face
; --- Language ---
tRegionAndLanguage=Region and language
tLanguage=Language
tTemperature=Temperature
tMetric=Celsius
tImperial=Fahrenheit
tStandard=Kelvin