[Variables]
SidebarContextTitle=#tEditWidgets#
SidebarContextAction=[!WriteKeyValue Variables SettingsTab "Widgets" "#@#Variables\Layout.inc"][!ToggleConfig "Monterey" "Settings.ini"][!ActivateConfig "Monterey" "Settings.ini"]
SidebarContextTitle2=#tDisableSidebar#
SidebarContextAction2=[!ShowFadeGroup "Monterey"][!DeactivateConfig "#CURRENTCONFIG#"]
SidebarContextTitle3=#tQuitRainmeter#
SidebarContextAction3=[!Quit]
SidebarContextTitle4=